# Generated by Django 5.2.7 on 2025-11-14 10:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_number",
                    models.BigIntegerField(
                        default=core.models.generate_8digit_id,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("software_dev", "ソフトウェア開発"),
                            ("video_edit", "ビデオ編集"),
                            ("graphic_design", "グラフィックデザイン"),
                            ("writing", "ライティング/コンテンツ作成"),
                            ("translation", "翻訳"),
                            ("consulting", "オンラインコンサルティング"),
                            ("digital_marketing", "デジタルマーケティング"),
                            ("data_analysis", "データ分析"),
                        ],
                        max_length=30,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("skill_required", models.TextField(blank=True)),
                ("deadline", models.DateField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "公開中"),
                            ("in_progress", "進行中"),
                            ("completed", "完了"),
                            ("canceled", "キャンセル"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "broker"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="中間人",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="依頼人",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "worker"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受託人",
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
    ]
