# Generated by Django 5.2.7 on 2025-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="price",
            field=models.PositiveIntegerField(
                help_text="金額（円、整数）", verbose_name="報酬"
            ),
        ),
    ]
