# Generated by Django 5.2.7 on 2025-12-06 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_task_title_brokerrequest"),
]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="coordinator",
        ),
        migrations.AddField(
            model_name="task",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "coordinator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinator_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="仲介者",
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorrequest",
            name="status",
            field=models.CharField(
                choices=[("value", "label"), ("value", "label"), ("value", "label")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "発注者"),
                    ("coordinator", "仲介者"),
                    ("worker", "受注者"),
                ],
                default="client",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "公開中"),
                    ("in_progress", "進行中"),
                    ("completed", "完了"),
                    ("canceled", "取り下げ"),
                ],
                default="open",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("software_dev", "ソフトウェア開発"),
                    ("video_edit", "動画編集"),
                    ("writing", "ライティング/コンテンツ作成"),
                    ("translation", "翻訳"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "worker"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="受注者",
            ),
        ),
    ]
