# Generated by Django 5.2.7 on 2025-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_task_broker_task_coordinator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinatorrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "処理待ち"),
                    ("approved", "承認済み"),
                    ("rejected", "拒否"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
