# Generated by Django 6.0 on 2025-12-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_workerrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credit_score",
            field=models.IntegerField(default=100),
        ),
    ]
